const BLOCK_SIZE = 256; // ^8
const DEVICE_SIZE = 65536; // ^16

const DIR_ENTRIES_IN_BLOCK = 8;
const BLOCKS_IN_BLOCK_MAP = 255;

const ZERO_BLOCK_ADDRESS = 255; // max value in 1 byte memory

export {
  BLOCK_SIZE,
  DEVICE_SIZE,
  DIR_ENTRIES_IN_BLOCK,
  BLOCKS_IN_BLOCK_MAP,
  ZERO_BLOCK_ADDRESS,
};
